language: ruby
rvm:
  - 2.0.0-p353
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
before_script:
  - cp ./config/database_test.yml ./config/database.yml
  - psql -c 'create database tarify_test' -U postgres
  #- npm install -g bower
  #- bower install
notifications:
    email: false
