defaults: &defaults
  sms_phone: ""
  app:
    title: Тарифы

    asset_host: http://tarify21.ru/

    default_url_options: &default_url_options
      host: tarify21.ru
      port: 80

  action_mailer: &action_mailer
    raise_delivery_errors: false
    default_url_options:
      <<: *default_url_options

  mailer_defaults: &mailer_defaults
    from: 'noreply@tarify21.ru'
    host: tarify21.ru

development:
  <<: *defaults
  action_mailer:
    <<: *action_mailer
    delivery_method: :smtp
    smtp_settings:
      address: localhost
      port: 1025   # mailcatcher
    raise_delivery_errors: true

test:
  <<: *defaults
  capybara:
    port: 57500

  action_mailer:
    <<: *action_mailer
    delivery_method: :test

production:
  <<: *defaults
  mailer_defaults:
    <<: *mailer_defaults

staging:
  <<: *defaults
  mailer_defaults:
    <<: *mailer_defaults
